Task 5

diff --git a/module2_task5/Makefile b/module2_task5/Makefile
--- a/module2_task5/Makefile
+++ b/module2_task5/Makefile
@@ -1,49 +1,52 @@
-GO=go
-TARGET=awesome-api
-RM=rm -rf
-MAKE=make
-COVERAGE=coverage
-HUGO=hugo
+build: hugo-build go-build  ## Build the project
 
-build:	## Generate the source code of the application to a binary.
-	$(MAKE) check && $(HUGO) && $(GO) build -o $(TARGET)
+go-build:   ## Compile the source code of the application to a binary
+	@go build
 
-run:	## Run the application in background by executing the binary.
-	./$(TARGET) >./$(TARGET).log 2>&1 &
+hugo-build:  ## Generate the website from the markdown and configuration files in the directory dist/ 
+	@hugo
 
-post:	## Create a new blog post whose filename and title come from the environment variables POST_TITLE and POST_NAME
-	$(HUGO) new posts/$(POST_NAME).md
-	sed -i '2s/.*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md
+run: build   ## Run the application in background by executing the binary
+	@./awesome-api > ./awesome-api.log 2>&1 &
 
-stop:	## Stop the application.
-	@pkill $(TARGET)
+post:   ## Create a new blog post whose filename and title come from the environment variables POST_TITLE and POST_NAME
+	@rm -Rf content/posts/$(POST_NAME).md
+	@hugo new posts/$(POST_NAME).md
+	@sed -i 's/title:.*/title: $(POST_TITLE)/' content/posts/$(POST_NAME).md
+	@sed -i 's/draft:.*/draft: "false"/' content/posts/$(POST_NAME).md
 
-clean:	## Stop the application. Delete the binary and the log file.
-	@if pgrep -x $(TARGET) > /dev/null; then \
-		pkill $(TARGET); \
-	fi
-	@$(RM) $(TARGET) $(TARGET).log $(COVERAGE)-units.out $(COVERAGE)-integrations.out dist/ *~
+stop:   ## Stop the application
+	@pkill awesome-api || true
 
-test:	## Test the application.
-	$(MAKE) unit-tests
-	$(MAKE) integration-tests
-	$(MAKE) validate
+clean: stop go-clean hugo-clean ## Cleanup project
 
-unit-tests: ## Run unit tests
-	go test -v -short -coverprofile=$(COVERAGE)-units.out
+hugo-clean:  ## Cleanup the content of the directory dist/
+	@rm -Rf dist/
 
-integration-tests: ## Run integration tests
-	go test -v -coverprofile=$(COVERAGE)-integrations.out
+go-clean:  ## Stop the application. Delete the binary and the log file:
+	@rm -f awesome-api awesome-api.log
+	@rm -f coverage-units.out
+	@rm -f coverage-integrations.out
 
-lint:	## Lint go lang code
-	golangci-lint run
+check: ## Check syntaxis and links
+	@find ./content -name \*.md -print0 | xargs -0 -n1 markdownlint
+	@find ./content -name \*.md -print0 | xargs -0 -n1 markdown-link-check
 
-check:	## Lint markdonw source, check dead links
-	markdownlint content/**/*.md
-	find content -name \*.md -print0 | xargs -0 -n1 markdown-link-check
+go-lint:   ## Catch errors without the need to compile or execute the application
+	@golangci-lint run
 
-validate:	## Validate the file dist/index.html using the command line Holberton’s W3C Validator.
-	python3 /opt/W3C-Validator/w3c_validator.py ./dist/index.html || true
+validate: ## Validate W3C HTML
+	@python3 /opt/W3C-Validator/w3c_validator.py ./dist/index.html 2>&1 || true
 
-help:	## Show this help usage.
-	@sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)
+lint: check go-lint  ## Staticly analyse the app source code and markdown files
+
+test: unit-tests integration-tests validate  ## Ensure that it behaves as expected
+
+unit-tests:  ## Run unit tests on web server
+	@go test -v -short -coverprofile=coverage-units.out
+
+integration-tests: ## Run integration tests on web server
+	@go test -v -coverprofile=coverage-integrations.out
+
+help:   ## Show this help usage
+	@cat Makefile | grep "^[a-z][a-z\-]*:.*##.*" | sed 's/:.*## /: /'
